### PR TITLE
fix(localforage): catch constructor's setDriver Promise

### LINKED ISSUE #631: LocalForage generates a rejected promise when imported in node.js
All I need to do is `import localforage from 'localforage'` in a node.js package to generate an error (no available storage found) - I don't have to config localforage or anything. The error itself is in a rejected, and uncaught, promise. The problem is that in future Node.js versions, a rejected promise may end up in the process terminating with a nonzero exit code.

My situation in particular is that I'm not actually using localforage, I'm just importing a package that can be configured to use it. With ES6 style import/export code, it's unclear how one would conditionally import stuff (vs require-style imports, which can happen inside an if-else block).

Ideally, the config stuff that throws this error would be moved into an initialize method or something, instead of [returning a new LocalForage()](https://github.com/localForage/localForage/blob/2f887aa69fcea10d409fc755c208ae0363a64190/src/localforage.js#L383) from the export command.

### PR DESCRIPTION
**Pull request by thgreasi**
Resolves #631 #626 #627.
@tofumatt I'm not sure how I could add tests for this (since it's a warning atm) but if you are fine with it we can merge it.

### CODE REVIEW

**Comment by ericeslinger** [comment]
I can confirm that this causes localforage to no longer generate an unhandled promise rejection on require() in a node environment.

**Comment by thgreasi** [comment]
@tofumatt gogo approval?

File: src/localforage.js [hunk 1]
```diff
@@ -116,7 +116,7 @@ class LocalForage {
         this._dbInfo = null;
 
         this._wrapLibraryMethodsWithReady();
-        this.setDriver(this._config.driver);
+        this.setDriver(this._config.driver).catch(() => {});
```
Comment (tofumatt) [inline src/localforage.js]: We could probably at least `console.error` this or something if `console.error` exists, just so we don't entirely fail silently (I could see that confusing people in the future).

Comment (thgreasi) [inline src/localforage.js]: I was thinking of that, but they are going to get the error at the moment they try to use any localforage method (the "no driver tests" still pass).
So for the developer:
* nothing actually changes with this PR
* localForage seems to do nothing on import, since the error during the default instance initialization is silenced and appears only when a method is used. After 3 duplicate tickets on this, I'm now starting thinking of this as a benefit.

**Comment by tofumatt** [comment]
Haha fair enough actually, I guess we can leave it out for now. 👍🏻

- Matthew Riley MacPherson | tofumatt.com

**Comment by jasan-s** [comment]
I am still getting an error : `(node:12884) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 6): Error: No available storage method found.` I'm using` v1.50`

**Comment by tofumatt** [comment]
@jasan-s I don't think that's related to this pull request. Could you please file a new issue?
